[package]
name = "bwt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
suffix_tree = "0.2.2"
suffix = "1.3.0"
version = "3.0.0"
quickcheck = "1.0.3"